project:
  type: website

website:
  title: "PIP Chart Gallery"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: globe
        text: PIP Home
        href: https://pip.worldbank.org  
      - icon: github
        text: Source Data
        href: https://github.com/GPID-WB/pip-chartbook.git
  page-footer:
    left: "© 2025 Poverty & Inequality Platform"
    right:
      - icon: globe
        href: https://pip.worldbank.org

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  python: false

